name: Dart Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Compile binaries
        run: dart compile exe bin/synk.dart
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
            name: artifacts-${{ matrix.os }}
            path: bin/synk.exe
